### ISSUE TITLE
Upload screenshots of the installed App

### ISSUE THREAD

**Issue by sridharjajoo** [sridharjajoo/NewsApp#1]
Currently the screenshots aren't being shown in the app. Install the app and upload screenshots for the same.

**Comment by rob729** [comment]
@sridharjajoo So where do you want the screenshots to be uploaded: Phone or Readme file of the project?

**Comment by sridharjajoo** [comment]
Readme file

**Comment by rob729** [comment]
[Screenshots](https://drive.google.com/open?id=1caR33ZAdpPThXF3YoUlj9RSfkq20HobQ)
@sridharjajoo Are these screenshots good enough to be added?

**Comment by sridharjajoo** [comment]
Yeah

**Comment by rob729** [comment]
@sridharjajoo  This is [link](https://github.com/rob729/NewsApp) to my fork repo of NewsApp.
Please tell me if I have updated the readme file correctly and should I send the PR now?

**Comment by sridharjajoo** [comment]
Try to fit all 3 images in 1 line
