### ISSUE TITLE
Add app icon

### ISSUE THREAD

**Issue by rob729** [sridharjajoo/NewsApp#11]

**Comment by rob729** [comment]
@sridharjajoo  what do you think about this issue?
Should I work on this issue?

**Comment by sridharjajoo** [comment]
Sure go ahead

**Comment by sridharjajoo** [comment]
Please send a few demos before making a PR

**Comment by rob729** [comment]
![](https://raw.githubusercontent.com/rob729/News-App/master/app/src/main/ic_launcher-web.png)

**Comment by rob729** [comment]
@sridharjajoo what do you think about this logo?

**Comment by sridharjajoo** [comment]
Design looks good. Maybe change the color background color from pink to blue(theme of the app)

**Comment by rob729** [comment]
#14 This is my PR for this issue.
@sridharjajoo Please review it.
