### ISSUE TITLE
Change the theme of Search bar

### ISSUE THREAD

**Issue by sridharjajoo** [sridharjajoo/NewsApp#2]
In the searchbar present in the search fragment, the search icon has a black color. Change the color to white

**Comment by sridharjajoo** [comment]
The Searchbar icon and the arrow is black. Change it to white

**Comment by rob729** [comment]
@sridharjajoo can you give me some hint regarding how to change the color of searchbar icon?

**Comment by sridharjajoo** [comment]
You can consult this medium article [link](https://android.jlelse.eu/how-to-change-menu-searchview-widget-icon-color-in-android-c9ff1043a41f)
