### ISSUE TITLE
Crash in SearchFragment 

### ISSUE THREAD

**Issue by sridharjajoo** [sridharjajoo/NewsApp#22]
There is a crash in SearchFragment when we search for a query when no internet is present. This needs to be resolved.

**Comment by rob729** [comment]
@sridharjajoo I am not facing this issue on my phone which is running on android Nougat

**Comment by rob729** [comment]
![](https://media.giphy.com/media/vvzFuSBXk6LcVMGjJW/giphy.gif)

**Comment by sridharjajoo** [comment]
I am facing the issue in Oreo. Add a network check anyways

**Comment by rob729** [comment]
Ok.
I am working on it.

**Comment by rob729** [comment]
@sridharjajoo Do you want to show any message if a user tries to search while no internet is present?
